version: '3.8'
 
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-container
    ports:
      - "3009:3009"
    environment:
      MONGO_URI: mongodb://mongo:27017/LoanApplication # Update the MongoDB URI to connect to the MongoDB service
    depends_on:
      - mongo
    # restart: unless-stopped
 
  mongo:
    container_name: mongodb-container
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]  # Health check command for MongoDB
      interval: 10s
      retries: 5